### ISSUE TITLE
Escape characters in strings not handled correctly

### ISSUE THREAD

**Issue by balsoft** [axellang/axel#79]
This axel file:

```
(module Main)

(= example "This should be a quotation mark: \"")

(= main (print example))
```

Transpiles to the following Haskell code:

```haskell
module Main where
import Axel
import qualified Prelude as GHCPrelude
import qualified Axel.Parse.AST as AST
example  = "This should be a quotation mark: ""
main  = (print example)
```

Which, for obvious reasons, does not compile.

Is this expected? I couldn't find anything specific about the way Axel is supposed to be treating escapes in the documentation, but the [String literals section](https://github.com/axellang/axel/wiki/Syntax-Reference#-string-literals) gives an example which includes an escape sequence.

**Comment by jgrosso** [comment]
This is rather embarrassing: Turns out, `\t` (and other escape sequences in general) are also being output inappropriately. In theory, I had golden tests which should've caught this issue. But, apparently, I only ever *visually* confirmed that the files looked like valid Haskell, instead of actually trying to run them in GHC. Among other things, this meant I couldn't easily tell when inappropriate whitespace like `\t` snuck in.

Action items for me:
- [ ] Fix escape sequences
- [ ] Add regression test based on the example above
- [ ] Add verification step for Haskell golden test files (see #80).

Thank you so much for catching this!

**Comment by jgrosso** [comment]
Next is for me to finish #80 and #81, and then I'll push a new release. Thanks again!
